version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7
    networks:
      - webnet
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  rcli:
    container_name: rcli
    image: redis:7
    networks:
      - webnet
    links:
      - redis
    command: redis-cli -h redis

networks:
  webnet:

volumes:
  postgres:
  redis:
    driver: local
